#API list for not to do app

###fetch all tickets

GET http://localhost:8000/api/v1/


# ### fetch single ticket
# GET http://localhost:8000/api/v1/6130a97baca58c9cd436196d

###create new ticket

POST http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task":"Coding Java",
    "hr":10
}


###update request

PATCH  http://localhost:8000/api/v1/
Content-Type: application/json

{
    "id":"6132d9ebf31bdc7e9d3f8c6f",
    "todo":false
}



###delete request

DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
    "ids":["6130a988aca58c9cd436196f"]
   

}


