#API list for not to do app

###fetch all tickets


GET http://localhost:8000/api/v1
# ### fetch single ticket
# GET hhtp://localhost:8000/api/v1/ticektid

###create new ticket

POST http://localhost:8000/api/v1/
Content-Type: application/json

{
    "task":"Coding JS",
    "hr":10
}


###update request

PATCH  http://localhost:8000/api/v1/
Content-Type: application/json

{
    "__id":"bchjsidh@dklsfmk.com",
    "todo":true
}



###delete request

DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
    "__id":"bchjsidh@dklsfmk.com"
   

}


